name: my first workflow

on: push

jobs: 
    first_job:
        run-on: ubuntu-latest
        steps: 
              - name: welocme message
                run: echo "mys first github"

              - name: list flies
                run: ls

              - name: read file
                run: cat README.md