name: my first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps: 
              - name: Checkout
                uses: actions/checkout@v4.1.1

              - name: welocme message
                run: echo "my first github"

              - name: list flies
                run: ls

              - name: read file
                run: cat README.md