name: Generate ASCII Artwork

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps: 
              - name: Checkout Repo
                uses: actions/checkout@v4.1.1

              - name: Install Cowsay Package
                run: sudo apt-get install cowsay -y
              
              - name: Executre Cowsay Program
                run: cowsay -f dragon "Run for Cover, I am a DRAGON.. RAWR" >> dragon.txt

              - name: Check the file's existance
                run: grep -i "dragon" dragon.txt
                
             - name: Read the flies
                run: cat dragon.txt

              - name: list the repo files
                run: ls -ltrha